### ISSUE TITLE
Undefined symbols for architecture x86_64: "_getrandom" on Mac OS X

### ISSUE THREAD

**Issue by Kogia-sima** [aspenluxxxy/nanorand-rs#16]
# :bug: Bug report

## Description

Compilation failed on Mac OS X on travis CI.

```console
Undefined symbols for architecture x86_64:
            "_getrandom", referenced from:
                nanorand::entropy::unix::entropy_from_system::h55951253ee7e2e83 in libnanorand-a83c92296e1a29be.rlib(nanorand-a83c92296e1a29be.nanorand.ow5fw3sw-cgu.6.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
```

Link: https://travis-ci.org/github/Kogia-sima/sailfish/jobs/750030765

Also, `getrandom` syscall is only available if the kernel supports. We must check the availability on runtime.

https://github.com/rust-random/getrandom/blob/master/src/linux_android.rs#L27-L38

## Environment

|Software|Version|
|--|--|
|rustc| 1.48.0 (stable) |
|OS|Mac OS X 10.13.6|

**Comment by aspenluxxxy** [comment]
for now can I suggest using the `getrandom` feature?

**Comment by Kogia-sima** [comment]
Yeah, it seems we need `getrandom` feature to compile on macOS

**Comment by aspenluxxxy** [comment]
honestly `getrandom` is always the preferred method of operation, it's just not default because zero-dep by default

**Comment by Kogia-sima** [comment]
@aspenluxxxy Thanks for your suggestion. I think it is better to call `getrandom` syscall on only linux or android, rather than `cfg(unix)`

**Comment by aspenluxxxy** [comment]
@Kogia-sima can you test the latest master?

**Comment by Kogia-sima** [comment]
@aspenluxxxy I am sorry for the delay in my response. Now I got an another error.

```console
$  cargo test --target x86_64-apple-darwin --manifest-path sailfish/Cargo.toml --no-default-features
    Updating crates.io index
    Updating git repository `https://github.com/aspenluxxxy/nanorand-rs.git`
 Downloading crates ...
  Downloaded version_check v0.9.2
  Downloaded ryu v1.0.5
  Downloaded itoap v0.1.0
   Compiling version_check v0.9.2
   Compiling ryu v1.0.5
   Compiling itoap v0.1.0
   Compiling nanorand v0.5.2-alpha.0 (https://github.com/aspenluxxxy/nanorand-rs.git#cee036fb)
error[E0425]: cannot find function `entropy_from_system` in module `crate::entropy`
  --> /Users/runner/.cargo/git/checkouts/nanorand-rs-844ffc2303295f82/cee036f/nanorand/src/rand/wyrand.rs:35:19
   |
35 |         crate::entropy::entropy_from_system(&mut entropy);
   |                         ^^^^^^^^^^^^^^^^^^^ not found in `crate::entropy`
   |
help: consider importing this function
   |
3  | use crate::entropy::darwin::entropy_from_system;
   |
```

https://github.com/Kogia-sima/sailfish/runs/1627227339

**Comment by aspenluxxxy** [comment]
try now

**Comment by Kogia-sima** [comment]
Thank you all your work! Now CI passed.

https://github.com/Kogia-sima/sailfish/runs/1627368931?check_suite_focus=true
